core/apps/user/urls.py
from apps.user.views import EmailVerificationView, LoginView, LogoutView, RegisterUserView
from django.urls import path

app_name = "auth"

urlpatterns = [
    path("email/", EmailVerificationView.as_view(), name="auth_request"),
    path("login-password/", LoginView.as_view(), name="login"),
    path("register/", RegisterUserView.as_view(), name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

core/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import URLPattern, URLResolver, include, path
from django.views import defaults as default_views
from django.views.generic import RedirectView

TURLList = list[URLPattern | URLResolver]


urlpatterns: TURLList = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("", RedirectView.as_view(pattern_name="cinema:home", permanent=False)),
    path("auth/", include("apps.user.urls", namespace="auth")),
    path("cinema/", include("apps.cinema.urls", namespace="cinema")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = urlpatterns + [path("__debug__/", include(debug_toolbar.urls))]

core/templates/components/footer.html
<footer style="background-color: rgba(0, 0, 0, 0.85);" class="text-light py-4 mt-5">
    <div class="container text-center">
        <div class="row">
            <div class="col-md-4 mb-3">
                <h5>CinemaHub</h5>
                <p class="mb-0">Your ultimate movie companion.</p>
            </div>
            <div class="col-md-4 mb-3">
                <h6>Quick Links</h6>
                <ul class="list-unstyled">
                    <li><a href="{% url 'cinema:home' %}" class="text-light text-decoration-none">Home</a></li>
                    <li><a href="#" class="text-light text-decoration-none">Blog</a></li>
                    <li><a href="#" class="text-light text-decoration-none">About Us</a></li>
                </ul>
            </div>
            <div class="col-md-4 mb-3">
                <h6>Follow Us</h6>
                <a href="#" class="text-light me-2"><i class="bi bi-twitter"></i></a>
                <a href="#" class="text-light me-2"><i class="bi bi-instagram"></i></a>
                <a href="#" class="text-light"><i class="bi bi-facebook"></i></a>
            </div>
        </div>
        <hr class="border-light">
        <p class="mb-0">&copy; {{ now|date:"Y" }} CinemaHub. All rights reserved.</p>
    </div>
</footer>

core/templates/components/iziToast.html
{% load static %}

<!-- iziToast -->
<!-- include this file after all script tags in your base.html file -->
<link rel="stylesheet" href="{% static 'css/iziToast.min.css' %}">
<script type="text/javascript" src="{% static 'js/iziToast.min.js' %}"></script>
<script>
  const TOAST_LEVEL_TAGS = {
    '{{DEFAULT_MESSAGE_LEVELS.ERROR}}': 'red',
    '{{DEFAULT_MESSAGE_LEVELS.INFO}}': 'blue',
    '{{DEFAULT_MESSAGE_LEVELS.SUCCESS}}': 'green',
    '{{DEFAULT_MESSAGE_LEVELS.WARNING}}': 'yellow',
  };
  const TOAST_LEVEL_BGS = {
    '{{DEFAULT_MESSAGE_LEVELS.ERROR}}': '#e74c3ce0',
    '{{DEFAULT_MESSAGE_LEVELS.INFO}}': '#3498dbe0',
    '{{DEFAULT_MESSAGE_LEVELS.SUCCESS}}': '#26b99ae0',
    '{{DEFAULT_MESSAGE_LEVELS.WARNING}}': '#f39c12e0',
  }
  const TOAST_LEVEL_ICONS = {
    '{{DEFAULT_MESSAGE_LEVELS.ERROR}}': 'fa fa-ban',
    '{{DEFAULT_MESSAGE_LEVELS.INFO}}': 'fa fa-info',
    '{{DEFAULT_MESSAGE_LEVELS.SUCCESS}}': 'fa fa-check',
    '{{DEFAULT_MESSAGE_LEVELS.WARNING}}': 'fa fa-warning',
  }
  const TOAST_LEVEL_FGS = {
    '{{DEFAULT_MESSAGE_LEVELS.ERROR}}': '#fff',
    '{{DEFAULT_MESSAGE_LEVELS.INFO}}': '#fff',
    '{{DEFAULT_MESSAGE_LEVELS.SUCCESS}}': '#fff',
    '{{DEFAULT_MESSAGE_LEVELS.WARNING}}': '#fff',
  }
  iziToast.settings({
      position: 'topLeft',
      timeout: 7000,
      closeOnClick: true,
  });
  const INFO_MESSAGE_OPTIONS = {
      color: TOAST_LEVEL_TAGS['{{DEFAULT_MESSAGE_LEVELS.INFO}}'],
      backgroundColor: TOAST_LEVEL_BGS['{{DEFAULT_MESSAGE_LEVELS.INFO}}'],
      messageColor: TOAST_LEVEL_FGS['{{DEFAULT_MESSAGE_LEVELS.INFO}}'],
      icon: TOAST_LEVEL_ICONS['{{DEFAULT_MESSAGE_LEVELS.INFO}}'],
      iconColor: TOAST_LEVEL_FGS['{{DEFAULT_MESSAGE_LEVELS.INFO}}'],
  }
  const SUCCESS_MESSAGE_OPTIONS = {
      color: TOAST_LEVEL_TAGS['{{DEFAULT_MESSAGE_LEVELS.SUCCESS}}'],
      backgroundColor: TOAST_LEVEL_BGS['{{DEFAULT_MESSAGE_LEVELS.SUCCESS}}'],
      messageColor: TOAST_LEVEL_FGS['{{DEFAULT_MESSAGE_LEVELS.SUCCESS}}'],
      icon: TOAST_LEVEL_ICONS['{{DEFAULT_MESSAGE_LEVELS.SUCCESS}}'],
      iconColor: TOAST_LEVEL_FGS['{{DEFAULT_MESSAGE_LEVELS.SUCCESS}}'],
  }
  const WARNING_MESSAGE_OPTIONS = {
      color: TOAST_LEVEL_TAGS['{{DEFAULT_MESSAGE_LEVELS.WARNING}}'],
      backgroundColor: TOAST_LEVEL_BGS['{{DEFAULT_MESSAGE_LEVELS.WARNING}}'],
      messageColor: TOAST_LEVEL_FGS['{{DEFAULT_MESSAGE_LEVELS.WARNING}}'],
      icon: TOAST_LEVEL_ICONS['{{DEFAULT_MESSAGE_LEVELS.WARNING}}'],
      iconColor: TOAST_LEVEL_FGS['{{DEFAULT_MESSAGE_LEVELS.WARNING}}'],
  }
  const ERROR_MESSAGE_OPTIONS = {
      color: TOAST_LEVEL_TAGS['{{DEFAULT_MESSAGE_LEVELS.ERROR}}'],
      backgroundColor: TOAST_LEVEL_BGS['{{DEFAULT_MESSAGE_LEVELS.ERROR}}'],
      messageColor: TOAST_LEVEL_FGS['{{DEFAULT_MESSAGE_LEVELS.ERROR}}'],
      icon: TOAST_LEVEL_ICONS['{{DEFAULT_MESSAGE_LEVELS.ERROR}}'],
      iconColor: TOAST_LEVEL_FGS['{{DEFAULT_MESSAGE_LEVELS.ERROR}}'],
  }
  function showInfoMessage(message, title = '', options = {}) {
    iziToast.info({
      title: title,
      message: message,
      ...INFO_MESSAGE_OPTIONS,
    });
  }
  function showSuccessMessage(message, title = '', options = {}) {
    iziToast.success({
      title: title,
      message: message,
      ...SUCCESS_MESSAGE_OPTIONS,
    });
  }
  function showWarningMessage(message, title = '', options = {}) {
    iziToast.warning({
      title: title,
      message: message,
      ...WARNING_MESSAGE_OPTIONS,
    });
  }
  function showErrorMessage(message, title = '', options = {}) {
    iziToast.error({
      title: title,
      message: message,
      ...ERROR_MESSAGE_OPTIONS,
    });
  }

  // Fetching and showing all messages
  {% for message in messages %}
    iziToast.show({
      message: '{{message.message}}',
      color: TOAST_LEVEL_TAGS['{{message.level}}'],
      backgroundColor: TOAST_LEVEL_BGS['{{message.level}}'],
      messageColor: TOAST_LEVEL_FGS['{{message.level}}'],
      icon: TOAST_LEVEL_ICONS['{{message.level}}'],
      iconColor: TOAST_LEVEL_FGS['{{message.level}}'],
    });
  {% endfor %}
</script>

core/templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark" style="position: fixed; top: 0; left: 0; width: 100%; z-index: 1000;
               color: white;">
    <div class="container">
        <a class="navbar-brand" href="{% url 'cinema:home' %}">CinemaHub</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <!-- Left nav items -->
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0 justify-content-center gap-3">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cinema:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Movies</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact Us</a>
                </li>
            </ul>

            <!-- User section -->
            <ul class="navbar-nav mb-2 mb-lg-0">
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarUserDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        {% if request.user.first_name and request.user.last_name %}
                        {{ request.user.first_name }} {{ request.user.last_name }}
                        {% else %}
                        {{ request.user.email }}
                        {% endif %}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarUserDropdown">
                        <li><a class="dropdown-item" href="#">Profile</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'auth:logout' %}">Logout</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth:auth_request' %}">Sign In</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>